### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by abetomo**

### CODE REVIEW

**Comment by abetomo** [comment]
Test fails on Mac.

```
TypeError: [plugin][register] cannot find plugin file: </usr/local/Cellar/groonga/13.0.1/lib/groonga/plugins/ruby/eval.so>
```

```
% ls -1 /usr/local/Cellar/groonga/13.0.1/lib/groonga/plugins/
functions
normalizers
query_expanders
suggest
token_filters
tokenizers
```

Is Ruby plugin no longer included on Mac?

**Comment by abetomo** [comment]
I'm confirming the details.

**Comment by kou** [comment]
It seems so: https://github.com/Homebrew/homebrew-core/pull/126947

**Comment by abetomo** [comment]
Thanks for the information!

**Pull request merged**
