### PR TITLE
Upgrade Node.js to use

### PR DESCRIPTION
**Pull request by abetomo**
The dependency Node.js was old, so I modified it to match the current Node.js.

I added the following modifications as well.
Because msgpack-node does not appear to be actively maintained.
https://github.com/msgpack/msgpack-node/commits/master

In opening this PR, I also fixed where I failed with Travis.

### CODE REVIEW

**Comment by abetomo** [comment]
@darashi Could you review it?

**Comment by darashi** [comment]
Thank you for sharing your work and pinging me. I haven't noticed this. I'm going to look in within a few days. I'm sorry for keep you waiting.

**Comment by darashi** [comment]
Looks great!  I've merged your PR and released it to npm. Thank you for your contribution.

I've confirmed that successfully builds and works on both Ubuntu and macOS. I think that now it's okay to drop msgpack dependency.
 
By the way, would you mind becoming a collaborator of this repository? I'm no longer active, so it would be great if it could happen.

**Comment by abetomo** [comment]
@darashi Thank you for review.

I'd like to contribute for nroonga in the future as well.
I am very happy to be a collaborator.

**Comment by darashi** [comment]
@abetomo I really appreciate that. I've added you to this repository and npm owner. Thank you again!

**Comment by abetomo** [comment]
I confirmed it. Thank you!

**Pull request merged**
