### PR TITLE
Drop support Node.js 6

### PR DESCRIPTION
**Pull request by abetomo**
* Node.js 6 is EOL
    * https://github.com/nodejs/Release#end-of-life-releases
* Also upgrade packages that require Node.js 8 or greater

### CODE REVIEW

**Comment by kou** [comment]
BTW, can we remove AppVeyor? It's slow.
Does our GitHub Actions configuration cover Windows cases enough?

**Comment by abetomo** [comment]
AppVeyor can be removed.
We can cover it with GitHub Actions settings.

**Comment by kou** [comment]
OK.
I'll remove AppVeyor configuration.

**Comment by abetomo** [comment]
Thank you!

https://github.com/nroonga/nroonga/blob/master/appveyor.yml#L13-L15
We haven't covered the 'platform' tests, but I think it's OK.

**Comment by kou** [comment]
I think so too.

**Pull request merged**
